# Generated by Django 4.2.20 on 2025-04-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniAvito', '0002_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание объявления'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='Animals_image/', verbose_name='Фото объявления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Document/', verbose_name='Ветеринарный паспорт'),
        ),
    ]
