# Generated by Django 4.2.20 on 2025-04-12 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AniAvito', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deal_completed_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deals', to=settings.AUTH_USER_MODEL),
        ),
    ]
